# Site settings
title: Medical Physics Canada
email: info@medphys-canada.org
description: >-
  Medical Physics Canada is a volunteer GitHub organization 
  dedicated to sharing software written by the medical physics across Canada. 
  Anyone around the world who wishes to contribute or ask questions is welcome!!!
baseurl: ""
url: "https://medphys-canada.github.io"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
